export const certifications = [
  { nameFa: "Prepare Data for Exploration", nameEn: "Prepare Data for Exploration", issuer: "Google / Coursera", group: "data", source: "linkedin-2026" },
  { nameFa: "Ask Questions to Make Data-Driven Decisions", nameEn: "Ask Questions to Make Data-Driven Decisions", issuer: "Google / Coursera", group: "data", source: "linkedin-2026" },
  { nameFa: "Share Data Through the Art of Visualization", nameEn: "Share Data Through the Art of Visualization", issuer: "Google / Coursera", group: "data", source: "linkedin-2026" },
  { nameFa: "The Fundamentals of Digital Marketing", nameEn: "The Fundamentals of Digital Marketing", issuer: "Google", group: "business", source: "linkedin-2026" },
  { nameFa: "Inbound Sales Certificate", nameEn: "Inbound Sales Certificate", issuer: "HubSpot", group: "business", source: "resume-1402" },
  { nameFa: "IBM Data Science Professional Certificate", nameEn: "IBM Data Science Professional Certificate", issuer: "IBM", group: "data", source: "resume-1402" },
  { nameFa: "Google IT Support Professional Certificate", nameEn: "Google IT Support Professional Certificate", issuer: "Google", group: "it", source: "resume-1402" },
  { nameFa: "Google Data Analytics Certificate", nameEn: "Google Data Analytics Certificate", issuer: "Google", group: "data", source: "resume-1402" },
  { nameFa: "CompTIA A+", nameEn: "CompTIA A+", issuer: "CompTIA", group: "it", source: "resume-1402" },
  { nameFa: "CompTIA Network+", nameEn: "CompTIA Network+", issuer: "CompTIA", group: "it", source: "resume-1402" },
  { nameFa: "AWS Fundamentals", nameEn: "AWS Fundamentals", issuer: "Amazon", group: "cloud", source: "resume-1402" },
  { nameFa: "Microsoft Azure Fundamentals", nameEn: "Microsoft Azure Fundamentals", issuer: "Microsoft", group: "cloud", source: "resume-1402" },
  { nameFa: "گواهی‌نامه CCNA", nameEn: "CCNA Certificate", issuer: "مجتمع فنی تهران / Tehran Institute of Technology", group: "network", source: "resume-1402" },
  { nameFa: "آشنایی با مالیات و نحوه تنظیم اظهارنامه مالیاتی", nameEn: "Taxation and Tax Return Preparation", issuer: "سازمان نظام صنفی رایانه‌ای", group: "business", source: "resume-1402" },
  { nameFa: "مهارت Freehand", nameEn: "Freehand Skills Certificate", issuer: "وزارت فرهنگ و ارشاد اسلامی", group: "creative", source: "resume-1402" },
  { nameFa: "مهارت Photoshop", nameEn: "Photoshop Skills Certificate", issuer: "سازمان آموزش فنی و حرفه‌ای کشور", group: "creative", source: "resume-1402" },
  { nameFa: "مهارت CorelDraw", nameEn: "CorelDraw Skills Certificate", issuer: "سازمان آموزش فنی و حرفه‌ای کشور", group: "creative", source: "resume-1402" },
  { nameFa: "ICDL مقدماتی و پیشرفته", nameEn: "ICDL — Basic and Advanced", issuer: "وزارت فرهنگ و ارشاد اسلامی", group: "it", source: "resume-1402" },
  { nameFa: "ISO 27001:2013", nameEn: "ISO 27001:2013", issuer: "USAS / ICS", group: "security", source: "resume-1402" },
  { nameFa: "استاندارد مدیریت امنیت اطلاعات", nameEn: "Information Security Management Standard", issuer: "ثبت‌شده در رزومه مهر ۱۴۰۲", group: "security", source: "resume-1402" },
  { nameFa: "مفاهیم سیستم مدیریت و اصول مستندسازی", nameEn: "Management System Concepts and Documentation Principles", issuer: "ثبت‌شده در رزومه مهر ۱۴۰۲", group: "security", source: "resume-1402" },
  { nameFa: "پیاده‌سازی سیستم مدیریت امنیت اطلاعات ISO/IEC 27001:2013", nameEn: "ISO/IEC 27001:2013 ISMS Implementation", issuer: "ثبت‌شده در رزومه مهر ۱۴۰۲", group: "security", source: "resume-1402" },
  { nameFa: "مبانی شناسایی، ارزیابی و مدیریت ریسک ISO/IEC 27005:2011", nameEn: "ISO/IEC 27005:2011 Risk Identification, Assessment and Management", issuer: "ثبت‌شده در رزومه مهر ۱۴۰۲", group: "security", source: "resume-1402" },
  { nameFa: "مشاوره سیستم مدیریت امنیت اطلاعات ISO/IEC 27001", nameEn: "ISO/IEC 27001 ISMS Consulting", issuer: "ثبت‌شده در رزومه مهر ۱۴۰۲", group: "security", source: "resume-1402" },
] as const;
