export const education = [
  {
    id: "msc-computer-systems-architecture",
    institutionFa: "دانشگاه آزاد اسلامی قزوین – دانشکده برق، رایانه و فناوری اطلاعات",
    institutionEn: "Qazvin Islamic Azad University",
    degreeFa: "کارشناسی ارشد مهندسی کامپیوتر – معماری سیستم‌های کامپیوتری",
    degreeEn: "Master's degree — Computer Systems Architecture",
    periodFa: "پایان: ۱۴۰۰",
    periodEn: "February 2018 – July 2021",
    sourceFa: "رزومه مهر ۱۴۰۲",
    sourceEn: "LinkedIn export / Mehr 1402 resume",
  },
  {
    id: "bsc-computer-hardware",
    institutionFa: "دانشگاه آزاد اسلامی قزوین – دانشکده برق، رایانه و فناوری اطلاعات",
    institutionEn: "Qazvin Islamic Azad University",
    degreeFa: "کارشناسی مهندسی کامپیوتر – سخت‌افزار",
    degreeEn: "Bachelor's degree — Computer Hardware Engineering",
    periodFa: "پایان: ۱۳۹۰",
    periodEn: "2007 – 2011",
    sourceFa: "رزومه مهر ۱۴۰۲",
    sourceEn: "LinkedIn export / Mehr 1402 resume",
  },
  {
    id: "pre-university-math",
    institutionFa: "پیش‌دانشگاهی ولیعصر (عج)",
    institutionEn: "Valiasr Pre-University",
    degreeFa: "ریاضی و فیزیک",
    degreeEn: "Mathematics and Physics",
    periodFa: "۱۳۷۶",
    periodEn: "1376 (as recorded in the Mehr 1402 resume)",
    sourceFa: "رزومه مهر ۱۴۰۲",
    sourceEn: "Mehr 1402 resume",
  },
  {
    id: "high-school-math",
    institutionFa: "دبیرستان دکتر علی شریعتی",
    institutionEn: "Dr. Ali Shariati High School",
    degreeFa: "دیپلم ریاضی فیزیک",
    degreeEn: "Mathematics and Physics Diploma",
    periodFa: "۱۳۷۵",
    periodEn: "1375 (as recorded in the Mehr 1402 resume)",
    sourceFa: "رزومه مهر ۱۴۰۲",
    sourceEn: "Mehr 1402 resume",
  },
] as const;
