export const founderCareerProfile = {
  nameFa: "امیر متفکر",
  nameEn: "Amir Motefaker",
  headlineFa: "بنیان‌گذار و مدیرعامل PrimeSYS | شبکه‌ساز کسب‌وکار | مذاکره‌کننده | منظم و پیگیر",
  headlineEn: "Founder & CEO @ PrimeSYS | Business Networker | Negotiator | Regular and Persistent",
  locationFa: "قزوین، ایران",
  locationEn: "Qazvin, Iran",
  technologySinceFa: "همراه فناوری از ۱۳۷۰؛ از DOS و سخت‌افزار تا داده، هوش مصنوعی و ساخت محصول.",
  technologySinceEn: "Working with technology since 1990, from DOS and hardware to data, AI and product building.",
  narrativeFa: [
    "مسیر من با کامپیوترهای IBM و DOS آغاز شد و با تحصیل در مهندسی سخت‌افزار و معماری سیستم‌های کامپیوتری ادامه پیدا کرد.",
    "در سال‌های بعد، تجربه زیرساخت و پشتیبانی فناوری اطلاعات با فروش، مذاکره، توسعه بازار و مدیریت تیم ترکیب شد.",
    "از ۱۳۹۷ به بعد، برنامه‌نویسی و تحلیل داده به بخش جدی‌تری از مسیرم تبدیل شد؛ با SQL، Python، R، Power BI و Tableau.",
    "امروز تمرکز من روی ساخت محصولات، پلتفرم‌ها و اکوسیستم‌هایی است که فناوری، داده، فروش و رشد را به هم متصل می‌کنند.",
  ],
  narrativeEn: [
    "My path began with IBM computers and DOS, followed by formal studies in computer hardware engineering and computer systems architecture.",
    "Over time, IT infrastructure and support experience combined with sales, negotiation, market development and team leadership.",
    "From 2018 onward, programming and data analysis became a deeper part of the journey through SQL, Python, R, Power BI and Tableau.",
    "Today my focus is building products, platforms and ecosystems that connect technology, data, sales and growth.",
  ],
  coreSkills: [
    "Entrepreneurship",
    "Networking",
    "Sales Management",
    "Negotiation",
    "Business Development",
    "CRM",
    "Excel",
    "SQL",
    "Python",
    "R",
    "Power BI",
    "Tableau",
    "IT Infrastructure",
  ],
  languages: [
    { nameFa: "فارسی", nameEn: "Persian", levelFa: "زبان مادری / دوزبانه", levelEn: "Native or Bilingual" },
    { nameFa: "انگلیسی", nameEn: "English", levelFa: "حرفه‌ای کامل", levelEn: "Full Professional" },
    { nameFa: "آلمانی", nameEn: "German", levelFa: "مقدماتی", levelEn: "Elementary" },
  ],
  source: "Profile.pdf (LinkedIn export)",
} as const;
