import Link from "next/link";
import { type Locale } from "@/content/founder-site";
import { getVerifiedEvidence } from "@/content/evidence-registry";
import { getProductCategory, getProductDisplayName, type Product } from "@/content/product-portfolio";
import { finalPublicProductPortfolio as products } from "@/content/final-public-product-portfolio";
import { primaryExperience, historicalResumeExperience, salesRepresentations, historicalMilestones } from "@/content/founder";
import { formatSiteNumber, localeDigits } from "@/lib/locale-format";
import styles from "./FounderHomeV2.module.css";
import v13 from "./FounderHomeV13.module.css";

const thesisPrinciples={fa:[["۰۱","مسئله، قبل از فناوری","ابتدا مسئله واقعی و رفتار کاربر را می‌فهمم؛ بعد سراغ ابزار می‌روم."],["۰۲","محصول، قبل از ادعا","خروجی قابل استفاده از هر روایت بازاریابی مهم‌تر است."],["۰۳","سیستم، قبل از ویژگی","محصول باید بتواند رشد کند، یاد بگیرد و به یک اکوسیستم بزرگ‌تر متصل شود."]],en:[["01","Problem before technology","Understand the real problem and user behavior before choosing the tool."],["02","Product before claims","A working product matters more than oversized marketing."],["03","Systems before features","Products should be able to grow, learn and connect into a wider ecosystem."]]} as const;
const marks:Record<string,string>={linkresan:"LR",farsio:"FA",fahmio:"FH",zobdino:"ZO",filmtrack:"FT",idehjo:"IJ",tasvia:"TV",vayran:"VA",darmic:"DA",restyar:"RY",primesys:"PS"};
const faMarks:Record<string,string>={linkresan:"لر",farsio:"فا",fahmio:"فه",zobdino:"زب",filmtrack:"فت",idehjo:"اج",tasvia:"تس",vayran:"وا",darmic:"دا",restyar:"رس",primesys:"پس"};
const industryMix={fa:[["هوش مصنوعی","۳"],["فناوری مالی","۲"],["سلامت دیجیتال","۲"],["گردشگری هوشمند","۲"],["یادگیری و آموزش","۲"],["رسانه و سرگرمی","۲"],["بازاریابی و فروش","۱"],["مدیریت و بهره‌وری","۱"],["داده و زیرساخت","۱"],["تجربه کاربری","۱"],["سایر حوزه‌ها","۱"]],en:[["Artificial Intelligence","3"],["FinTech & Finance","2"],["Digital Health","2"],["Smart Tourism","2"],["Learning & Education","2"],["Media & Entertainment","2"],["Marketing & Sales","1"],["Management & Productivity","1"],["Data & Infrastructure","1"],["User Experience","1"],["Other sectors","1"]]} as const;
function lifecycle(status:Product["status"],locale:Locale){const labels={fa:{live:"فعال",development:"در حال توسعه",discovery:"در مرحله بررسی",concept:"ایده اولیه","to-confirm":"در حال تأیید"},en:{live:"Live",development:"In development",discovery:"Discovery",concept:"Concept","to-confirm":"To confirm"}} as const;return labels[locale][status];}
export default function FounderHome({locale}:{locale:Locale}){const fa=locale==="fa";const evidence=getVerifiedEvidence();const totalProducts=products.length;const careerRecords=primaryExperience.length+historicalResumeExperience.length+salesRepresentations.length+historicalMilestones.length;const verified=Math.max(careerRecords,evidence.length);const featured=products;return <main className={`${styles.home} ${v13.home}`}>
<section className={`${styles.hero} ${v13.hero}`}><div className={`wrap ${styles.heroShell} ${v13.heroShell}`}>
<div className={`${styles.heroCopy} ${v13.heroCopy}`}><div className={`${styles.identityLine} ${v13.identityLine}`}><i/><span>{fa?"امیر متفکر · علاقه‌مند به فناوری":"Amir Motefaker · Tech-savvy"}</span></div><h1 className={v13.headline}>{fa?<>محصول نمی‌سازم که فقط دیده شود؛ <em>سیستم‌هایی می‌سازم که اثر بگذارند.</em></>:<>I don’t build products just to be seen. <em>I build systems that create impact.</em></>}</h1><p className={`${styles.heroLead} ${v13.heroLead}`}>{fa?"من امیر متفکر هستم؛ کارآفرین و سازنده مجموعه‌ای از محصولات مستقل در حوزه‌های هوش مصنوعی، فناوری مالی، آموزش، سلامت و گردشگری.":"I’m Amir Motefaker—an entrepreneur building independent products across AI, FinTech, education, health and tourism."}</p><div className={styles.heroActions}><Link href={`/${locale}/products`} className={`${styles.primaryAction} ${v13.action} ${v13.primaryAction}`}>{fa?"مشاهده محصولات":"Explore products"}<span>‹</span></Link><Link href={`/${locale}/resume`} className={`${styles.secondaryAction} ${v13.action} ${v13.secondaryAction}`}>{fa?"مسیر حرفه‌ای من":"My professional journey"}<span>‹</span></Link></div>
<div className={`${styles.heroMetrics} ${v13.heroMetrics}`}><div><strong>{formatSiteNumber(totalProducts,locale)}</strong><span>{fa?"محصول در اکوسیستم":"Products in the ecosystem"}</span></div><div><strong>{fa?"۳۰+":"30+"}</strong><span>{fa?"سال در مسیر فناوری":"Years in technology"}</span></div><div><strong>{fa?"۱۰+":"10+"}</strong><span>{fa?"حوزه فناوری متنوع":"Diverse technology sectors"}</span></div><div><strong>{formatSiteNumber(verified,locale)}+</strong><span>{fa?"شاهد و سابقه ثبت‌شده":"Verified records"}</span></div></div></div>
<aside className={`${styles.heroVisual} ${v13.heroVisual}`}><div className={v13.industryCanvas}><div className={v13.interestRail}><span/><strong>{fa?"علاقه‌مند به فناوری":"TECH-SAVVY"}</strong></div><div className={v13.industryHeader}><span>{fa?"حوزه‌های فناوری":"TECHNOLOGY SECTORS"}</span><small>{fa?"بیش از ۱۰ حوزه تخصصی":"10+ specialist sectors"}</small></div><div className={v13.industryBody}><div className={v13.donutWrap}><div className={v13.donut}><div><strong>{formatSiteNumber(totalProducts,locale)}</strong><span>{fa?"محصول":"products"}</span></div></div></div><div className={v13.industryLegend}>{industryMix[locale].map(([label,count],index)=><div key={label}><i className={v13[`sector${(index%8)+1}`]}/><span>{label}</span><strong>{count}</strong></div>)}</div></div><div className={v13.industryFoot}><span>{fa?"محصولات مستقل در صنایع متنوع فناوری":"Independent products across diverse technology industries"}</span><strong>{fa?"بیش از ۳۰ سال تجربه فناوری":"30+ years in technology"}</strong></div></div></aside></div></section>
<section className={styles.venturesSection}><div className={`wrap ${styles.sectionIntro}`}><span>{fa?"اکوسیستم محصولات":"Product ecosystem"}</span><div><h2>{fa?"یازده محصول مستقل؛ یک نگاه مشترک به ساخت فناوری.":"Eleven independent products. One product-building philosophy."}</h2><p>{fa?"از زیرساخت و فروش تا آموزش، رسانه، سلامت، سفر و فناوری مالی؛ هر محصول صفحه اختصاصی، وضعیت شفاف و مسیر رشد خودش را دارد.":"From infrastructure and commerce to education, media, health, travel and fintech—every product has its own case study, current state and growth path."}</p></div></div><div className={`wrap ${styles.ventureGrid} ${v13.ventureGrid}`}>{featured.map((product,index)=><Link href={`/${locale}/products/${product.slug}`} key={product.slug} className={`${styles.ventureCard} ${v13.ventureCard}`}><div className={styles.ventureTop}><div className={styles.ventureMark}>{fa?(faMarks[product.slug]??"مح"):(marks[product.slug]??product.slug.slice(0,2).toUpperCase())}</div><span>{localeDigits(String(index+1).padStart(2,"0"),locale)} · {lifecycle(product.status,locale)}</span></div><div className={`${styles.ventureContent} ${v13.ventureContent}`}><div><h3>{getProductDisplayName(product,locale)}</h3>{product.domain?<small className="ltr">{product.domain}</small>:null}</div><p>{fa?product.shortDescriptionFa:product.shortDescriptionEn}</p></div><div className={`${styles.ventureFoot} ${v13.ventureFoot}`}><span>{getProductCategory(product,locale)}</span><strong>{fa?"مطالعه محصول":"Case study"} ↗</strong></div></Link>)}</div><div className={`wrap ${styles.allProducts}`}><Link href={`/${locale}/products`}>{fa?`مشاهده پرتفوی کامل ${formatSiteNumber(totalProducts,locale)} محصول`:`Explore the full portfolio of ${formatSiteNumber(totalProducts,locale)} products`}<span>↗</span></Link></div></section>
{evidence.length>0&&<section className={styles.proofSection}><div className={`wrap ${styles.sectionIntro}`}><span>{fa?"شواهد اجرا":"Proof"}</span><div><h2>{fa?"خروجی واقعی، مهم‌تر از ادعاست.":"Real output matters more than claims."}</h2></div></div><div className={`wrap ${styles.proofGrid}`}>{evidence.slice(0,6).map((item,index)=><article className={styles.proofCard} key={item.id}><span>{localeDigits(String(index+1).padStart(2,"0"),locale)}</span><h3>{fa?item.titleFa:item.titleEn}</h3>{item.url?<a href={item.url} target="_blank" rel="noopener noreferrer">{fa?"بررسی مدرک":"Inspect evidence"} ↗</a>:null}</article>)}</div></section>}
<section className={styles.thesisSection}><div className={`wrap ${styles.sectionIntro}`}><span>{fa?"رویکرد":"Approach"}</span><div><h2>{fa?"فناوری ابزار است؛ نقطه شروع، مسئله است.":"Technology is a tool. The starting point is the problem."}</h2></div></div><div className={`wrap ${styles.thesisGrid}`}>{thesisPrinciples[locale].map(([index,title,detail])=><article className={styles.thesisCard} key={title}><span>{index}</span><h3>{title}</h3><p>{detail}</p></article>)}</div></section><section className={styles.contactSection}><div className={`wrap ${styles.contactPanel}`}><span>{fa?"ارتباط":"Contact"}</span><h2>{fa?"برای همکاری و ساخت محصولات جدید گفتگو کنیم.":"Let's talk about building and collaborating."}</h2><div><Link href={`/${locale}/contact`} className={styles.primaryAction}>{fa?"شروع گفتگو":"Start a conversation"}<span>↗</span></Link></div></div></section></main>;}
